# Site Settings
title: textHEAVY
description: A portfolio and personal site for nifisher
url: "http://nifisher.github.io"  
author:
  name: "nifisher"
  email: "fisherni@gmail.com"
  url: "https://nifisher.github.iom"

# Build Settings
markdown: kramdown
baseurl: /
source: .
destination: ./_site
permalink: /plan/:year/:month/:day/:title
timezone: America/New_York

# Custom variables
version: "1.0.0"

# Options
custom_header: false # injuect custom header with header-custom.html
custom_nav_footer: false # inject custom nav footer with nav-footer-custom.html
reverse: true # true puts nav on left, false on right
