# Site Settings
title: textHEAVY
description: A portfolio and personal site for nifisher
url: "http://nifisher.github.io"  
author:
	name: "nifisher"
	email: "fisherni@gmail.com"
	url: "http://nifisher.github.io"

# Build Settings
markdown: kramdown
baseurl: /
source: .
destination: ./_site
permalink: /blog/:year/:month/:day/:title
timezone: America/New_York

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
